const Roles = [
  { label: "backend", category: "Engineering" },
  { label: "frontend", category: "Engineering" },
  { label: "fullstack", category: "Engineering" },
  { label: "iOS", category: "Engineering" },
  { label: "flutter", category: "Engineering" },
  { label: "react native", category: "Engineering" },
  { label: "android", category: "Engineering" },
  { label: "tech lead", category: "Engineering" },
  { label: "dev-ops", category: "Engineering" },
  { label: "data engineer", category: "Engineering" },
  { label: "data science", category: "Engineering" },
  { label: "computer-vision", category: "Engineering" },
  { label: "nlp", category: "Engineering" },
  { label: "deep-learning", category: "Engineering" },
  { label: "test / qa", category: "Engineering" },
  { label: "Web3", category: "Engineering" },
  { label: "deep-learning", category: "Engineering" },
  { label: "sre", category: "Engineering" },
  { label: "data-infrastructure", category: "Engineering" },
  { label: "designer", category: "Design" },
  { label: "design manager", category: "Design" },
  { label: "graphic designer", category: "Design" },
  { label: "product designer", category: "Design" },
  { label: "product manager", category: "Product" },
  { label: "Operations Manager", category: "Operations" },
  { label: "founder’s office/chief Of staff", category: "Operations" },
  { label: "sales development representative", category: "Sales" },
  { label: "account executive", category: "Sales" },
  { label: "account manager", category: "Sales" },
  { label: "digital marketing manager", category: "Marketing" },
  { label: "growth hacker", category: "Marketing" },
  { label: "Marketing", category: "Marketing" },
  { label: "product marketing manager", category: "Marketing" },
  { label: "hardware", category: "Other Engineering" },
  { label: "mechanical", category: "Other Engineering" },
  { label: "Systems", category: "Other Engineering" },
  { label: "business analyst", category: "Business Analyst" },
  { label: "data analyst", category: "Data Analyst" },
  { label: "project manager", category: "Project Manager" },
  { label: "management", category: "Management" },
  { label: "legal", category: "Legal" },
  { label: "hr", category: "hr" },
  { label: "finance", category: "Finance" },
];

const EMPLOYEES = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "201-500",
  "500+",
];

const EXPERIENCE = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
const TYPE = ["Remote", "Hybrid", "In-office"];
const TECH_STACK = [
  "Python",
  "Java",
  "GoLang",
  "Ruby/Rails",
  "C++",
  "Kotlin",
  "Django",
  "C#",
  "GraphQL",
  "Flask",
  "Typescript",
  "AWS",
  "Javascript",
  "Rust",
  "NodeJS",
  "React",
];
const SALARY = ["0L", "10L", "20L", "30L", "40L", "50L"];
export const FILTER_FIELDS = [
  {
    key: "roles",
    label: "Roles",
    type: "multiselect",
    grouped: true,
    options: Roles,
  },
  {
    key: "empNo",
    label: "Number Of Employees",
    type: "multiselect",
    options: EMPLOYEES,
  },
  { key: "exp", label: "Experience", type: "select", options: EXPERIENCE },
  { key: "type", label: "", type: "multiselect", options: TYPE },
  {
    key: "tech",
    label: "Tech Stack",
    type: "multiselect",
    options: TECH_STACK,
  },
  {
    key: "salary",
    label: "Minimum Base Pay Salary",
    type: "select",
    options: SALARY,
  },
  { key: "company", label: "Search Company Name", type: "text" },
];
